#!/usr/bin/env bash
# Displays information about subdomains
if [ $# = 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        record_type=$(dig "$sub.$1" | awk '/ANSWER SECTION/ {getline; print $4}')
        destination=$(dig "$sub.$1" | awk '/ANSWER SECTION/ {getline; print $5}')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
elif [ $# = 2 ]; then
    record_type=$(dig "$2.$1" | awk '/ANSWER SECTION/ {getline; print $4}')
    destination=$(dig "$2.$1" | awk '/ANSWER SECTION/ {getline; print $5}')
    echo "The subdomain $2 is a $record_type record and points to $destination"
fi
