#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
count=1
while ((count <= 10)); do
    if ((count == 9)); then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done
